spring:
  config:
    import: application-hybrid-eval.yaml
---
server:
  port: 9094
unique-name: "-cs-scifact-v1"
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ragent_eval_pool_scifact_v1?client_encoding=UTF8
  data:
    redis:
      database: 12
rag:
  storage:
    kb-bucket: ragent-cs-scifact-v1-sources
    asset-bucket: ragent-cs-scifact-v1-assets
  keyword:
    es:
      index: cs_pool_scifact_hybrid_v1
